<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.green-code-initiative</groupId>
    <artifactId>creedengo-java-plugin</artifactId>
    <version>${revision}</version>

    <packaging>sonar-plugin</packaging>

    <name>creedengo - Java language</name>
    <description>Provides rules to reduce the environmental footprint of your Java programs</description>
    <inceptionYear>2024</inceptionYear>

    <url>https://github.com/green-code-initiative/creedengo-java</url>
    <organization>
        <name>green-code-initiative</name>
        <url>https://github.com/green-code-initiative</url>
    </organization>

    <licenses>
        <license>
            <name>GPL v3</name>
            <url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:https://github.com/green-code-initiative/creedengo-java</connection>
        <developerConnection>scm:git:https://github.com/green-code-initiative/creedengo-java</developerConnection>
        <url>https://github.com/green-code-initiative/creedengo-java</url>
        <tag>HEAD</tag>
    </scm>

    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/green-code-initiative/creedengo-java/issues</url>
    </issueManagement>

    <properties>

        <!--
            Default version when disabling Maven `maven-git-versioning-extension` extension
            cf. https://github.com/qoomon/maven-git-versioning-extension#intellij&#45;&#45;-multi-modules-projects
        -->
        <revision>current-SNAPSHOT</revision>

        <!-- Helps ensure build reproducibility (cf. https://maven.apache.org/guides/mini/guide-reproducible-builds.html) -->
        <!--suppress UnresolvedMavenProperty -->
        <project.build.outputTimestamp>${git.commit.timestamp.datetime}</project.build.outputTimestamp>

        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <!-- to prevent message: system modules path not set in conjunction with -source 11 -->
        <maven.compiler.release>${java.version}</maven.compiler.release>

        <!-- <encoding>UTF-8</encoding> -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <!-- Custom property to skip only unit tests (not integration tests) -->
        <skip.unit.tests>false</skip.unit.tests>

        <sonar.organization>green-code-initiative</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>

        <!-- Minimal version of the SonarQube APIs for `creedengo-java-plugin`  -->
        <sonarqube-plugin-api-min.version>9.9.0.65466</sonarqube-plugin-api-min.version>

        <!-- Version of the SonarQube APIs used by `creedengo-java-plugin` -->
        <sonar.plugin.api.version>13.0.0.3026</sonar.plugin.api.version>

        <!-- Version of `sonar-java-plugin` that `creedengo-java-plugin` depends on  -->
        <sonarjava.version>8.40.0.46617</sonarjava.version>
        <!-- last version 8.41.0.47177 is NON OK for JDK 17 because compiled only for JDK 21 -->
<!--        <sonarjava.version>8.41.0.47177</sonarjava.version>-->

        <sonar-analyzer-commons.version>2.30.0.5193</sonar-analyzer-commons.version>

        <sonar-packaging.version>1.25.1.3002</sonar-packaging.version>

        <!-- Version of creedengo rules specifications implemented by this plugin -->
        <creedengo-rules-specifications.version>3.2.0</creedengo-rules-specifications.version>

        <!-- Version of creedengo integration test system -->
        <creedengo-integration-test.version>0.7.0</creedengo-integration-test.version>

        <!-- URL of the Maven repository where sonarqube will be downloaded -->
        <test-it.orchestrator.artifactory.url>https://repo1.maven.org/maven2</test-it.orchestrator.artifactory.url>
        <!-- You can override this property to keep SonarQube instance running and to manually use it -->
        <test-it.sonarqube.keepRunning>false</test-it.sonarqube.keepRunning>

        <!-- KO -->
        <!-- <test-it.sonarqube.version>9.8.0.63668</test-it.sonarqube.version> -->

        <!-- Version of `sonarqube` used by integration tests (you can override this value to perform matrix compatibility tests) -->
        <!-- OK JDK17 but KO with JDK21 -->
        <!-- KO < v2.2.x -->
        <!-- <test-it.sonarqube.version>9.9.0.65466</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>9.9.8.100196</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>10.1.0.73245</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>10.1.0.73491</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>10.2.0.77647</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>10.7.0.96327</test-it.sonarqube.version> -->

        <!-- OK JDK17 / KO with JDK21 / OK >= v2.2.x INIT -->
        <!-- <test-it.sonarqube.version>24.12.0.100206</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.1.0.102122</test-it.sonarqube.version> -->

        <!-- OK JDK 17 / JDK 21 / OK >= v2.2.x-->
        <!-- <test-it.sonarqube.version>25.2.0.102705</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.3.0.104237</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.4.0.105899</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.5.0.107428</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.9.0.112764</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>25.12.0.117093</test-it.sonarqube.version> -->

        <!-- OK but only with JDK 21 -->
        <!-- <test-it.sonarqube.version>26.1.0.118079</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>26.2.0.119303</test-it.sonarqube.version> -->
        <!-- <test-it.sonarqube.version>26.6.0.123539</test-it.sonarqube.version> -->
        <test-it.sonarqube.version>26.7.0.124771</test-it.sonarqube.version>

        <!-- Version of `sonar-java-plugin` used by integration tests (you can override this value to perform matrix compatibility tests) -->
        <test-it.sonarjava.version>${sonarjava.version}</test-it.sonarjava.version>

        <!-- SonarQube server listening port. Leave this property blank to automatically choose an available port. -->
        <test-it.sonarqube.port />

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.green-code-initiative</groupId>
            <artifactId>creedengo-rules-specifications</artifactId>
            <version>${creedengo-rules-specifications.version}</version>
            <classifier>java</classifier>
        </dependency>

        <dependency>
            <groupId>org.sonarsource.java</groupId>
            <artifactId>sonar-java-plugin</artifactId>
            <version>${sonarjava.version}</version>
            <type>sonar-plugin</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.sonarsource.api.plugin</groupId>
            <artifactId>sonar-plugin-api</artifactId>
            <version>${sonar.plugin.api.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.sonarsource.analyzer-commons</groupId>
            <artifactId>sonar-analyzer-commons</artifactId>
            <version>${sonar-analyzer-commons.version}</version>
        </dependency>

        <!-- for security on regex patterns : https://github.com/google/re2j -->
        <dependency>
            <groupId>com.google.re2j</groupId>
            <artifactId>re2j</artifactId>
            <version>1.8</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.19</version>
            <!-- To keep with this scope otherwise logging system will be not ok on custom plugins -->
            <scope>provided</scope>
        </dependency>

        <!-- TEST sources dependencies -->

        <!-- Dependencies used by integration tests -->
        <!-- in first place to get last version of assertj-core -->
        <dependency>
            <groupId>org.green-code-initiative</groupId>
            <artifactId>creedengo-integration-test</artifactId>
            <version>${creedengo-integration-test.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.sonarsource.java</groupId>
            <artifactId>java-checks-testkit</artifactId>
            <version>${sonarjava.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>6.1.3</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.23.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <!-- <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>3.11.0.3922</version>
                </plugin>
            </plugins>
        </pluginManagement> -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.16.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <skip>${skip.unit.tests}</skip>
                    <systemPropertyVariables>
                        <testfiles.path>src/it/test-projects/creedengo-java-plugin-test-project/src/main/java/org/greencodeinitiative/creedengo/java/checks</testfiles.path>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.15</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonarsource.sonar-packaging-maven-plugin</groupId>
                <artifactId>sonar-packaging-maven-plugin</artifactId>
                <version>${sonar-packaging.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <pluginKey>creedengojava</pluginKey>
                    <pluginClass>org.greencodeinitiative.creedengo.java.JavaPlugin</pluginClass>
                    <sonarLintSupported>true</sonarLintSupported>
                    <pluginApiMinVersion>${sonarqube-plugin-api-min.version}</pluginApiMinVersion>
                    <skipDependenciesPackaging>true</skipDependenciesPackaging>
                    <jreMinVersion>${java.version}</jreMinVersion>
                    <requiredForLanguages>java</requiredForLanguages>
                    <archive>
                        <manifestEntries>
                            <Implementation-Build>${buildNumber}</Implementation-Build>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <!-- plugin to generate a unique build number for sonar-packaging-maven-plugin : usage of buildNumber variable -->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <getRevisionOnlyOnce>true</getRevisionOnlyOnce>
                    <revisionOnScmFailure>0</revisionOnScmFailure>
                </configuration>
            </plugin>
            <plugin>
                <!-- shade plugin configuration is on parent pom.xml because of use for other modules -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <minimizeJar>true</minimizeJar>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
                                <filter>
                                    <artifact>org.sonarsource.analyzer-commons:sonar-analyzer-commons:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>com.google.re2j:re2j:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/**</exclude>
                                    </excludes>
                                </filter>
                                <filter>
                                    <artifact>org.green-code-initiative:creedengo-rules-specifications:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/**</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- FOR TUs -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.10.0</version>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.slf4j</groupId>
                                    <artifactId>slf4j-api</artifactId>
                                    <version>2.0.19</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.apache.commons</groupId>
                                    <artifactId>commons-collections4</artifactId>
                                    <version>4.6.0</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>javax</groupId>
                                    <artifactId>javaee-api</artifactId>
                                    <version>8.0.1</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.springframework</groupId>
                                    <artifactId>spring-webmvc</artifactId>
                                    <version>7.0.9</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.springframework</groupId>
                                    <artifactId>spring-web</artifactId>
                                    <version>7.0.9</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.springframework</groupId>
                                    <artifactId>spring-context</artifactId>
                                    <version>7.0.9</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.springframework.data</groupId>
                                    <artifactId>spring-data-jpa</artifactId>
                                    <!-- TU KO with 3.X and 4.X -->
<!--                                    <version>4.1.1</version>-->
<!--                                    <version>3.5.13</version>-->
                                    <version>2.7.18</version>
                                    <type>jar</type>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.springframework.data</groupId>
                                    <artifactId>spring-data-commons</artifactId>
                                    <version>2.7.18</version>
                                    <!-- KO with version 3.x et 4.x -->
                                    <!-- <version>3.0.0</version> -->
                                    <!-- <version>3.5.3</version> -->
<!--                                    <version>4.1.1</version>-->
                                    <type>jar</type>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.build.directory}/test-jars</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                    <version>5.1.2</version>
                <configuration>
                    <properties>
                        <owner>Green Code Initiative</owner>
                        <email>https://green-code-initiative.org</email>
                    </properties>
                    <licenseSets>
                        <licenseSet>
                            <header>com/mycila/maven/plugin/license/templates/GPL-3.txt</header>
                            <includes>
                                <include>${project.basedir}/src/**/*.java</include>
                            </includes>
                            <excludes>
                                <exclude>${project.basedir}/src/it/test-projects/**</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                </configuration>
                <executions>
                    <execution>
                        <id>validate</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>validate</phase>
                    </execution>
                </executions>
            </plugin>
            <!-- activate integration tests -->
            <plugin>
                <!-- add integration test sources into test classpath -->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>add-integration-test-sources</id>
                        <phase>process-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/src/it/java</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-integration-test-resources</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/it/resources</directory>
                                </resource>
                                <resource>
                                    <filtering>true</filtering>
                                    <directory>${project.basedir}/src/it/resources-filtered</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <!-- Execute integration tests -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                        <configuration>
                            <systemPropertyVariables>
                                <test-it.sonarqube.keepRunning>${test-it.sonarqube.keepRunning}</test-it.sonarqube.keepRunning>
                                <test-it.orchestrator.artifactory.url>${test-it.orchestrator.artifactory.url}</test-it.orchestrator.artifactory.url>
                                <test-it.sonarqube.version>${test-it.sonarqube.version}</test-it.sonarqube.version>
                                <test-it.sonarqube.port>${test-it.sonarqube.port}</test-it.sonarqube.port>
                                <!-- Comma separated list of plugins (`groupId|artifactId|version` or `file:///`) to install in SonarQube instance before lunching integration tests -->
                                <test-it.plugins>
                                    ${project.baseUri}/target/${project.artifactId}-${project.version}.jar,
                                    org.sonarsource.java:sonar-java-plugin:${test-it.sonarjava.version},
                                </test-it.plugins>
                                <!-- Comma separated JSON profile file URIs to load -->
                                <test-it.additional-profile-uris>
                                    ${project.baseUri}/src/main/resources/org/greencodeinitiative/creedengo/java/creedengo_way_profile.json,
                                </test-it.additional-profile-uris>
                                <!-- Comma separated paths of "test projects" to analyze. Syntaxe: `sonar.projectKey|sonar.projectName|project.pomUri` -->
                                <test-it.test-projects>
                                    org.green-code-initiative:creedengo-java-plugin-test-project|creedengo Java Sonar Plugin Test Project|${project.baseUri}/src/it/test-projects/creedengo-java-plugin-test-project/pom.xml,
                                </test-it.test-projects>
                                <!-- Comma separated list of profiles to associate to each "test project". Syntaxe: `language:profileName` -->
                                <test-it.test-project-profile-by-language>
                                    java|creedengo way,
                                </test-it.test-project-profile-by-language>
                            </systemPropertyVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>keep-running</id>
            <properties>
                <test-it.sonarqube.keepRunning>true</test-it.sonarqube.keepRunning>
<!--                <test-it.sonarqube.port>9000</test-it.sonarqube.port>-->
                <test-it.sonarqube.port>33333</test-it.sonarqube.port>
            </properties>
        </profile>
    </profiles>
</project>
